name: Docker Image CI to YC!

on:
  push:
    branches: [ "GA-Action-Branch-1" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    #- name: Login to Yandex Cloud Container Registry
    #  id: login-cr
    #  uses: yc-actions/yc-cr-login@v2
    #  with:
    #    yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
    - name: Login to Yandex Cloud Container Registry
      uses: docker/login-action@v2
      with:
        registry: cr.yandex
        username: _token
        password:  ${{ secrets.YC_SA_JSON_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: cr.yandex/crp0lp04nhb31icik022/clockbox:latest

    #- name: Build, tag, and push image to Yandex Cloud Container Registry
    #  env:
    #    CR_REGISTRY: crp0lp04nhb31icik022
    #    CR_REPOSITORY: clockbox
    #    IMAGE_TAG: ${{ github.sha }}
    #  run: |
    #    docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:latest .
    #    docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:latest